schema_version: 1

scenes:
  city:
    min_height: 0.10
    max_height: 0.50
    cost_scaling_factor: 1.5
    inflation_radius: 0.4

  forest:
    min_height: -0.15
    max_height: 0.50
    cost_scaling_factor: 1.0
    inflation_radius: 1.5

  airport:
    min_height: 0.33
    max_height: 0.50
    cost_scaling_factor: 1.5
    inflation_radius: 0.4
