schema_version: 1
coordinate_mode: shared_absolute
pose_groups:
  group_01:
    resolved: true
    robots:
      go2_1:
        x: -25.58
        y: 2.30
        z: 0.80
        yaw: 0.13
      go2_2:
        x: -34.96
        y: -5.82
        z: 0.80
        yaw: 2.61
      go2_3:
        x: 54.10
        y: -6.02
        z: 0.80
        yaw: -1.94
  group_02:
    resolved: true
    robots:
      go2_1:
        x: -19.53
        y: 14.96
        z: 0.80
        yaw: -1.01
      go2_2:
        x: -29.08
        y: -6.90
        z: 0.80
        yaw: 2.76
      go2_3:
        x: 58.10
        y: -21.63
        z: 0.80
        yaw: 2.41
  group_03:
    resolved: true
    robots:
      go2_1:
        x: -12.54
        y: -6.44
        z: 0.80
        yaw: 1.58
      go2_2:
        x: -32.08
        y: 2.39
        z: 0.80
        yaw: -2.75
      go2_3:
        x: 57.24
        y: -5.03
        z: 0.80
        yaw: -2.15
  group_04:
    resolved: true
    robots:
      go2_1:
        x: -4.57
        y: -3.49
        z: 0.80
        yaw: 2.40
      go2_2:
        x: -31.98
        y: -0.32
        z: 0.80
        yaw: -3.01
      go2_3:
        x: 45.95
        y: -7.08
        z: 0.80
        yaw: -1.03
  group_05:
    resolved: true
    robots:
      go2_1:
        x: -12.86
        y: 15.25
        z: 0.80
        yaw: -1.55
      go2_2:
        x: -34.46
        y: 2.80
        z: 0.80
        yaw: -2.61
      go2_3:
        x: 47.75
        y: -3.35
        z: 0.80
        yaw: -1.33
  group_06:
    resolved: true
    robots:
      go2_1:
        x: -16.09
        y: 14.40
        z: 0.80
        yaw: -1.25
      go2_2:
        x: -35.09
        y: 3.08
        z: 0.80
        yaw: -2.54
      go2_3:
        x: 52.55
        y: -2.25
        z: 0.80
        yaw: -1.72
  group_07:
    resolved: true
    robots:
      go2_1:
        x: -15.40
        y: 15.72
        z: 0.80
        yaw: -1.34
      go2_2:
        x: -33.13
        y: 1.96
        z: 0.80
        yaw: -2.75
      go2_3:
        x: 51.16
        y: -6.46
        z: 0.80
        yaw: -1.63
  group_08:
    resolved: true
    robots:
      go2_1:
        x: -0.99
        y: 4.44
        z: 0.80
        yaw: -3.10
      go2_2:
        x: -33.77
        y: -8.80
        z: 0.80
        yaw: 2.43
      go2_3:
        x: 62.37
        y: -18.24
        z: 0.80
        yaw: 2.87
  group_09:
    resolved: true
    robots:
      go2_1:
        x: -21.33
        y: 10.94
        z: 0.80
        yaw: -0.68
      go2_2:
        x: -33.50
        y: -0.37
        z: 0.80
        yaw: -2.99
      go2_3:
        x: 41.63
        y: -5.54
        z: 0.80
        yaw: -0.81
  group_10:
    resolved: true
    robots:
      go2_1:
        x: -15.94
        y: 15.73
        z: 0.80
        yaw: -1.30
      go2_2:
        x: -33.02
        y: 3.52
        z: 0.80
        yaw: -2.62
      go2_3:
        x: 50.19
        y: -5.12
        z: 0.80
        yaw: -1.52
  group_11:
    resolved: true
    robots:
      go2_1:
        x: -15.76
        y: -7.99
        z: 0.80
        yaw: 1.32
      go2_2:
        x: -33.74
        y: -5.59
        z: 0.80
        yaw: 2.70
      go2_3:
        x: 50.35
        y: -2.22
        z: 0.80
        yaw: -1.55
