<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>world_to_grid</name>
  <version>0.1.0</version>
  <description>Generate conservative 2D occupancy maps from Gazebo SDF collision geometry.</description>
  <maintainer email="tinsleybalmer@gmail.com">bit</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>assimp</build_depend>
  <build_depend>ignition-math6</build_depend>
  <build_depend>tinyxml2</build_depend>
  <exec_depend>gazebo</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
