"""Generate the nine fixed test worlds from route YAML and base worlds."""

import argparse
import math
import re
from pathlib import Path

from go2_test_framework.common.config import ROUTES, SCENES, load_routes


ACTOR_PATTERN = re.compile(
    r'(<actor\s+name=["\']walking_target["\'][^>]*>)(.*?)(</actor>)',
    re.DOTALL,
)
TRAJECTORY_PATTERN = re.compile(
    r'(<trajectory\s+id=["\']0["\']\s+type=["\']walking["\'][^>]*>)(.*?)(</trajectory>)',
    re.DOTALL,
)


def _unwrap(angle, reference):
    while angle - reference > math.pi:
        angle -= 2.0 * math.pi
    while angle - reference < -math.pi:
        angle += 2.0 * math.pi
    return angle


def route_waypoints(route):
    """Return (time, x, y, yaw) waypoints with explicit turn intervals."""
    points = list(route["points"])
    if route["traversal"] == "closed":
        travel = points + [points[0]]
    else:
        travel = points + list(reversed(points[:-1]))
    segments = list(zip(travel, travel[1:]))
    headings = [math.atan2(end[1] - start[1], end[0] - start[0]) for start, end in segments]
    unwrapped = [headings[0]]
    for heading in headings[1:]:
        unwrapped.append(_unwrap(heading, unwrapped[-1]))
    closing_heading = _unwrap(headings[0], unwrapped[-1])

    current_time = 0.0
    output = [(current_time, travel[0][0], travel[0][1], unwrapped[0])]
    for index, (start, end) in enumerate(segments):
        current_time += math.hypot(end[0] - start[0], end[1] - start[1]) / route["speed"]
        output.append((current_time, end[0], end[1], unwrapped[index]))
        next_heading = unwrapped[index + 1] if index + 1 < len(unwrapped) else closing_heading
        current_time += route["turn_duration"]
        output.append((current_time, end[0], end[1], next_heading))
    return output


def render_trajectory(route, scene, route_name):
    marker = "provisional" if route["provisional"] else "resolved"
    lines = [
        "\n          <!-- Generated by go2_test_framework; ",
        f"scene={scene} route={route_name} status={marker}. -->",
    ]
    for timestamp, x, y, yaw in route_waypoints(route):
        lines.append(
            "\n          <waypoint><time>%.3f</time><pose>%.6f %.6f 0 0 0 %.6f</pose></waypoint>"
            % (timestamp, x, y, yaw)
        )
    lines.append("\n        ")
    return "".join(lines)


def generate_world(base_text, route, scene, route_name):
    actor_match = ACTOR_PATTERN.search(base_text)
    if actor_match is None:
        raise ValueError("base world must contain exactly one walking_target actor")
    if ACTOR_PATTERN.search(base_text, actor_match.end()) is not None:
        raise ValueError("base world contains multiple walking_target actors")
    actor_body = actor_match.group(2)
    matches = list(TRAJECTORY_PATTERN.finditer(actor_body))
    if len(matches) != 1:
        raise ValueError("walking_target must contain exactly one walking trajectory")
    replacement = lambda match: match.group(1) + render_trajectory(route, scene, route_name) + match.group(3)
    new_actor_body = TRAJECTORY_PATTERN.sub(replacement, actor_body, count=1)
    content = base_text[:actor_match.start(2)] + new_actor_body + base_text[actor_match.end(2):]
    return re.sub(r"[ \t]+$", "", content, flags=re.MULTILINE)


def generate_all(config_path, repo_root, output_dir, check=False):
    routes = load_routes(config_path)
    repo_root = Path(repo_root).resolve()
    output_dir = Path(output_dir)
    mismatches = []
    generated = []
    for scene in SCENES:
        source = repo_root / routes[scene]["base_world"]
        try:
            base_text = source.read_text(encoding="utf-8")
        except OSError as error:
            raise ValueError(f"failed to read base world {source}: {error}") from error
        for route_name in ROUTES:
            output = output_dir / f"{scene}_{route_name}.world"
            content = generate_world(base_text, routes[scene]["routes"][route_name], scene, route_name)
            generated.append(output)
            if check:
                try:
                    existing = output.read_text(encoding="utf-8")
                except OSError:
                    existing = None
                if existing != content:
                    mismatches.append(output)
            else:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_text(content, encoding="utf-8")
    if mismatches:
        names = ", ".join(str(path) for path in mismatches)
        raise ValueError(f"generated worlds are out of date: {names}")
    return generated


def _default_package_root():
    return Path(__file__).resolve().parents[1]


def _discover_repo_root(package_root):
    for candidate in (package_root, *package_root.parents):
        if (candidate / "QY_MODEL" / "target_seek").is_file():
            return candidate
    raise ValueError("cannot discover repository root; pass --repo-root")


def main(argv=None):
    package_root = _default_package_root()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=package_root / "config/parameters/target_routes.yaml")
    parser.add_argument("--repo-root", type=Path)
    parser.add_argument("--output-dir", type=Path, default=package_root / "worlds")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    repo_root = args.repo_root or _discover_repo_root(package_root)
    generated = generate_all(args.config, repo_root, args.output_dir, check=args.check)
    action = "checked" if args.check else "generated"
    print(f"{action} {len(generated)} test worlds")


if __name__ == "__main__":
    main()
